# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wls-22/labProg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wls-22/labProg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wls-22/labProg/CMakeFiles /home/wls-22/labProg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wls-22/labProg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named labProg

# Build rule for target.
labProg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 labProg
.PHONY : labProg

# fast build rule for target.
labProg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/build
.PHONY : labProg/fast

binarysearchtree.o: binarysearchtree.c.o
.PHONY : binarysearchtree.o

# target to build an object file
binarysearchtree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/binarysearchtree.c.o
.PHONY : binarysearchtree.c.o

binarysearchtree.i: binarysearchtree.c.i
.PHONY : binarysearchtree.i

# target to preprocess a source file
binarysearchtree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/binarysearchtree.c.i
.PHONY : binarysearchtree.c.i

binarysearchtree.s: binarysearchtree.c.s
.PHONY : binarysearchtree.s

# target to generate assembly for a file
binarysearchtree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/binarysearchtree.c.s
.PHONY : binarysearchtree.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/main.c.s
.PHONY : main.c.s

matrix.o: matrix.c.o
.PHONY : matrix.o

# target to build an object file
matrix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/matrix.c.o
.PHONY : matrix.c.o

matrix.i: matrix.c.i
.PHONY : matrix.i

# target to preprocess a source file
matrix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/matrix.c.i
.PHONY : matrix.c.i

matrix.s: matrix.c.s
.PHONY : matrix.s

# target to generate assembly for a file
matrix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/matrix.c.s
.PHONY : matrix.c.s

shape.o: shape.c.o
.PHONY : shape.o

# target to build an object file
shape.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/shape.c.o
.PHONY : shape.c.o

shape.i: shape.c.i
.PHONY : shape.i

# target to preprocess a source file
shape.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/shape.c.i
.PHONY : shape.c.i

shape.s: shape.c.s
.PHONY : shape.s

# target to generate assembly for a file
shape.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/shape.c.s
.PHONY : shape.c.s

stack.o: stack.c.o
.PHONY : stack.o

# target to build an object file
stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/stack.c.o
.PHONY : stack.c.o

stack.i: stack.c.i
.PHONY : stack.i

# target to preprocess a source file
stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/stack.c.i
.PHONY : stack.c.i

stack.s: stack.c.s
.PHONY : stack.s

# target to generate assembly for a file
stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/stack.c.s
.PHONY : stack.c.s

test.o: test.c.o
.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i
.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s
.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/labProg.dir/build.make CMakeFiles/labProg.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... labProg"
	@echo "... binarysearchtree.o"
	@echo "... binarysearchtree.i"
	@echo "... binarysearchtree.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... matrix.o"
	@echo "... matrix.i"
	@echo "... matrix.s"
	@echo "... shape.o"
	@echo "... shape.i"
	@echo "... shape.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

